name: CI

on:
  push:
    branches:
      - main
      - feature/**
      - pet-*
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4

      - name: Konfiguracja PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Instalacja zależności
        run: composer install --no-interaction --prefer-dist

      - name: Uruchomienie testów
        run: php bin/phpunit

      - name: Uruchomienie PHPStan
        run: vendor/bin/phpstan analyse